1-run_inline

diff --git a/python-hello_world/0-run b/python-hello_world/0-run
--- a/python-hello_world/0-run
+++ b/python-hello_world/0-run
@@ -1,3 +1,8 @@
-#!/usr/bin/env python3
-# This script runs the Python script defined in the PYFILE environment variable 
+#!/bin/bash
+print("Best School")
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable is not set."
+    exit 1
+fi
+
 python3 "$PYFILE"
